version: "3.7"
services:
  mongodb_container:
    image: mongo:latest
    container_name: "${MONGO_CONTAINER_NAME}"
    hostname: "${MONGO_HOSTNAME}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data_container:/data/db

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

volumes:
  mongodb_data_container:
  redis-data:
  redis-conf:
