version: "3.7"
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
